# Generated by Django 5.2 on 2025-08-29 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_rename_fecha_calificacion_fecha_creacion'),
        ('administracion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asistencia', 'Certificado de Asistencia'), ('aprobacion', 'Certificado de Aprobación'), ('examen', 'Certificado de Examen'), ('otro', 'Otro Certificado')], max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('codigo_verificacion', models.CharField(max_length=50, unique=True)),
                ('contenido', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.DeleteModel(
            name='Certificacion',
        ),
    ]
