# Generated by Django 5.2 on 2025-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_certificado_delete_certificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('asistencia', 'Certificado de Asistencia'), ('aprobacion', 'Certificado de Aprobación'), ('examen', 'Certificado de Examen'), ('regularidad', 'Certificado de Regularidad'), ('alumno_regular', 'Certificado de Alumno Regular'), ('buen_comportamiento', 'Certificado de Buen Comportamiento'), ('otro', 'Otro Certificado')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='certificado',
            table='administracion_certificados',
        ),
    ]
