# Generated by Django 5.2 on 2025-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_certificado_options_alter_certificado_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('asistencia', 'Certificado de Asistencia'), ('aprobacion', 'Certificado de Aprobación'), ('examen', 'Certificado de Examen'), ('alumno_regular', 'Certificado de Alumno Regular'), ('buen_comportamiento', 'Certificado de Buen Comportamiento'), ('otro', 'Otro Certificado')], max_length=30),
        ),
    ]
