# Generated by Django 5.2 on 2025-08-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_remove_usuario_persona_persona_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
