# Generated by Django 5.2 on 2025-08-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_remove_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='roles',
        ),
    ]
