# Generated by Django 5.2 on 2025-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_remove_persona_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_alumno',
            field=models.BooleanField(default=False),
        ),
    ]
