# Generated by Django 5.2 on 2025-08-19 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_persona_es_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='es_alumno',
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institucional.persona')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'institucional_empleados',
            },
            bases=('institucional.persona',),
        ),
    ]
