# Generated by Django 5.2 on 2025-08-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0007_remove_persona_usuario_remove_persona_es_alumno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
