# Generated by Django 5.2 on 2025-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0009_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(verbose_name=200)),
                ('direccion', models.CharField(verbose_name=200)),
                ('nro_telefono', models.CharField(verbose_name=200)),
                ('nro_celular', models.CharField(verbose_name=200)),
                ('logo', models.FileField(upload_to='img/')),
            ],
        ),
    ]
