# Generated by Django 5.2 on 2025-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0010_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nro_celular',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nro_telefono',
            field=models.CharField(max_length=200),
        ),
    ]
