# Generated by Django 5.2 on 2025-09-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0011_alter_institucion_direccion_alter_institucion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.FileField(upload_to='app/static/img/'),
        ),
    ]
