# Generated by Django 5.2 on 2025-12-06 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0013_auditoriaacceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('objeto_repr', models.CharField(max_length=255)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Datos',
                'verbose_name_plural': 'Auditoría de Datos',
                'db_table': 'institucional_auditoria_datos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='audit_datos_fecha_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='audit_datos_usuario_idx'), models.Index(fields=['modelo', '-fecha_hora'], name='audit_datos_modelo_idx'), models.Index(fields=['tipo_accion', '-fecha_hora'], name='audit_datos_tipo_idx')],
            },
        ),
    ]
