# Generated by Django 5.2 on 2025-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0014_auditoria_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitoVerificadorVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100, unique=True)),
                ('dvv', models.CharField(max_length=255)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dígito Verificador Vertical',
                'verbose_name_plural': 'Dígitos Verificadores Verticales',
                'db_table': 'institucional_dvv',
            },
        ),
    ]
