# Generated by Django 5.2 on 2025-12-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0015_digitoverificadorvertical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name': 'Institución', 'verbose_name_plural': 'Institución'},
        ),
        migrations.AddField(
            model_name='institucion',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='url_ayuda',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Ayuda'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='url_documentacion',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Documentación'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='url_soporte',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Soporte'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='app/static/img/'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nro_celular',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Número de Celular'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nro_telefono',
            field=models.CharField(max_length=200, verbose_name='Número de Teléfono'),
        ),
    ]
