# Generated by Django 5.2 on 2025-12-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0016_alter_institucion_options_institucion_email_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='url_ayuda',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='url_documentacion',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='url_soporte',
        ),
    ]
