# Generated by Django 5.2 on 2025-12-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0017_remove_institucion_url_ayuda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='institucion',
            name='archivo_manual',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Manual de Usuario (PDF)'),
        ),
    ]
