# Generated by Django 5.2 on 2025-12-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0018_preguntafrecuente_institucion_archivo_manual'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
