# Generated by Django 5.2 on 2025-08-13 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='plan_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.planestudio'),
        ),
        migrations.AddField(
            model_name='comision',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
    ]
