# Generated by Django 5.2 on 2025-08-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name': 'Comision', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelTable(
            name='comision',
            table='academico_comisiones',
        ),
        migrations.AlterModelTable(
            name='materia',
            table='academico_materias',
        ),
    ]
