# Generated by Django 5.2 on 2025-08-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_comision_options_alter_materia_options_and_more'),
        ('institucional', '0005_remove_persona_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institucional.persona'),
        ),
    ]
