# Generated by Django 5.2 on 2025-08-19 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_comision_docente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comision',
            old_name='horario',
            new_name='horario_fin',
        ),
        migrations.AddField(
            model_name='comision',
            name='dia_cursado',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='comision',
            name='horario_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comision',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=50),
        ),
    ]
