# Generated by Django 5.2 on 2025-08-19 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_rename_horario_comision_horario_fin_and_more'),
        ('institucional', '0007_remove_persona_usuario_remove_persona_es_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institucional.persona')),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.estadosalumno')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'institucional_alumnos',
            },
            bases=('institucional.persona',),
        ),
    ]
