# Generated by Django 5.2 on 2025-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_estadosalumno_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
