# Generated by Django 5.2 on 2025-08-19 12:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_alter_alumno_promedio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionesAlumnosComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=datetime.datetime(2025, 8, 19, 9, 49, 49, 95020))),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.comision')),
            ],
        ),
    ]
