# Generated by Django 5.2 on 2025-08-19 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_inscripcionesalumnoscomisiones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcionesalumnoscomisiones',
            options={'verbose_name': 'Inscripcion del alumno en comisiones', 'verbose_name_plural': 'Inscripiones de alumnos en comisiones'},
        ),
        migrations.AlterField(
            model_name='inscripcionesalumnoscomisiones',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 9, 52, 26, 28009)),
        ),
        migrations.AlterModelTable(
            name='inscripcionesalumnoscomisiones',
            table='institucional_inscripciones_alumnos_comisiones',
        ),
    ]
