# Generated by Django 5.2 on 2025-08-19 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_alter_inscripcionesalumnoscomisiones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionesalumnoscomisiones',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 9, 53, 1, 341107)),
        ),
    ]
