# Generated by Django 5.2 on 2025-08-19 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_inscripcionesalumnoscomisiones_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionesalumnoscomisiones',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 10, 17, 42, 896631)),
        ),
    ]
