# Generated by Django 5.2 on 2025-08-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_inscripcionesalumnoscomisiones_creado'),
        ('administracion', '0002_initial'),
        ('institucional', '0009_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosalumno',
            options={'verbose_name': 'Estado del Alumno', 'verbose_name_plural': 'Estados de Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcionesalumnoscomisiones',
            options={'verbose_name': 'Inscripción del alumno en comisiones', 'verbose_name_plural': 'Inscripciones de alumnos en comisiones'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comision',
            name='aula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comision',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='inscripcionesalumnoscomisiones',
            name='estado_inscripcion',
            field=models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('RETIRADO', 'Retirado'), ('FINALIZADO', 'Finalizado')], default='INSCRIPTO', max_length=20),
        ),
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.estadosalumno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='dia_cursado',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')]),
        ),
        migrations.AlterField(
            model_name='comision',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institucional.persona'),
        ),
        migrations.AlterField(
            model_name='inscripcionesalumnoscomisiones',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together={('codigo', 'materia', 'turno', 'dia_cursado')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionesalumnoscomisiones',
            unique_together={('alumno', 'comision')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('codigo', 'plan_estudio')},
        ),
    ]
