# Generated by Django 5.2 on 2025-08-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_alter_estadosalumno_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionesalumnoscomisiones',
            name='estado_inscripcion',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LIBRE', 'Libre')], default='REGULAR', max_length=20),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARCIAL', 'Parcial'), ('TP', 'Trabajo Práctico'), ('FINAL', 'Final'), ('CONCEPTO', 'Concepto')], max_length=20)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('alumno_comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.inscripcionesalumnoscomisiones')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('alumno_comision', 'tipo')},
            },
        ),
    ]
