# Generated by Django 5.2 on 2025-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_alter_inscripcionesalumnoscomisiones_estado_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada')], default='EN_CURSO', max_length=20),
            preserve_default=False,
        ),
    ]
