# Generated by Django 5.2 on 2025-08-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_comision_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='creditos',
        ),
    ]
