# Generated by Django 5.2 on 2025-08-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_remove_materia_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_presente', models.BooleanField(default=False)),
                ('fecha_asistencia', models.DateField(auto_now_add=True)),
                ('alumno_comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.inscripcionesalumnoscomisiones')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
