# Generated by Django 5.2 on 2025-08-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_anioacademico_alter_comision_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comision',
            name='anio_academico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academico.anioacademico'),
        ),
        migrations.AlterModelTable(
            name='comision',
            table=None,
        ),
    ]
