# Generated by Django 5.2 on 2025-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0020_alter_asistencia_fecha_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='correlativas',
            field=models.ManyToManyField(blank=True, to='academico.materia'),
        ),
    ]
