# Generated by Django 5.2 on 2025-08-28 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_materia_correlativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 14, 37, 16, 865127)),
            preserve_default=False,
        ),
    ]
