# Generated by Django 5.2 on 2025-08-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0022_calificacion_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
    ]
