# Generated by Django 5.2 on 2025-09-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_rename_fecha_calificacion_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InscripcionesAlumnosComisiones',
            new_name='InscripcionAlumnoComision',
        ),
    ]
