# Generated by Django 5.2 on 2025-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0024_rename_inscripcionesalumnoscomisiones_inscripcionalumnocomision'),
        ('institucional', '0012_alter_institucion_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_asistencia',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='es_dia_clase',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='calendarioacademico',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_creacion',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('PARCIAL', 'Parcial'), ('TP', 'Trabajo Práctico'), ('FINAL', 'Final'), ('CONCEPTO', 'Concepto')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='comision',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='comision',
            name='dia_cursado',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], db_index=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada')], db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno_comision', 'fecha_asistencia')},
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['alumno_comision', 'fecha_asistencia'], name='asist_alumno_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha_asistencia', 'esta_presente'], name='asist_fecha_presente_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarioacademico',
            index=models.Index(fields=['anio_academico', 'fecha', 'es_dia_clase'], name='cal_anio_fecha_clase_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['alumno_comision', 'tipo'], name='calif_alumno_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['fecha_creacion'], name='calif_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['docente', 'estado'], name='comision_docente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='comision',
            index=models.Index(fields=['dia_cursado', 'estado'], name='comision_dia_estado_idx'),
        ),
    ]
