# Generated by Django 5.2 on 2025-11-25 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0025_alter_asistencia_fecha_asistencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionalumnocomision',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el cierre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionalumnocomision',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se cerró la materia', null=True),
        ),
        migrations.AddField(
            model_name='inscripcionalumnocomision',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota final calculada al cerrar la materia', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcionalumnocomision',
            name='estado_inscripcion',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LIBRE', 'Libre'), ('APROBADA', 'Aprobada'), ('DESAPROBADA', 'Desaprobada')], default='REGULAR', max_length=20),
        ),
    ]
