# Generated by Django 5.2 on 2025-11-26 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0026_inscripcionalumnocomision_cerrada_por_and_more'),
        ('institucional', '0013_auditoriaacceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateTimeField(help_text='Fecha y hora del examen')),
                ('fecha_limite_inscripcion', models.DateTimeField(help_text='Fecha límite para inscribirse a la mesa')),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta para inscripciones'), ('CERRADA', 'Cerrada (no acepta más inscripciones)'), ('FINALIZADA', 'Finalizada (examen tomado)')], default='ABIERTA', max_length=20)),
                ('cupo_maximo', models.PositiveIntegerField(default=50, help_text='Cantidad máxima de alumnos que pueden rendir')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.anioacademico')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_creadas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_examen', to='academico.materia')),
                ('tribunal', models.ManyToManyField(help_text='Docentes que conforman el tribunal', related_name='tribunales_examen', to='institucional.persona')),
            ],
            options={
                'verbose_name': 'Mesa de Examen',
                'verbose_name_plural': 'Mesas de Examen',
                'db_table': 'academico_mesas_examen',
                'ordering': ['-fecha_examen'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionMesaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('REGULAR', 'Regular (aprobó cursada)'), ('LIBRE', 'Libre (no aprobó cursada o perdió regularidad)')], help_text='Condición con la que rinde (Regular o Libre)', max_length=20)),
                ('estado_inscripcion', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('AUSENTE', 'Ausente'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado')], default='INSCRIPTO', max_length=20)),
                ('nota_examen', models.DecimalField(blank=True, decimal_places=2, help_text='Nota del examen final', max_digits=4, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('mesa_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_mesa', to='academico.mesaexamen')),
            ],
            options={
                'verbose_name': 'Inscripción a Mesa de Examen',
                'verbose_name_plural': 'Inscripciones a Mesas de Examen',
                'db_table': 'academico_inscripciones_mesa_examen',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.AddIndex(
            model_name='mesaexamen',
            index=models.Index(fields=['materia', 'fecha_examen'], name='mesa_materia_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='mesaexamen',
            index=models.Index(fields=['estado', 'fecha_examen'], name='mesa_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionmesaexamen',
            index=models.Index(fields=['mesa_examen', 'alumno'], name='insc_mesa_alumno_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionmesaexamen',
            index=models.Index(fields=['estado_inscripcion'], name='insc_mesa_estado_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionmesaexamen',
            unique_together={('mesa_examen', 'alumno')},
        ),
    ]
