# Generated by Django 5.2 on 2025-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0027_mesaexamen_inscripcionmesaexamen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anioacademico',
            name='cierre_cursada_habilitado',
            field=models.BooleanField(default=False, help_text='Habilita a los docentes para cerrar notas de cursada'),
        ),
        migrations.AddField(
            model_name='anioacademico',
            name='fecha_limite_cierre',
            field=models.DateField(blank=True, help_text='Fecha límite para cierre de notas', null=True),
        ),
        migrations.AddField(
            model_name='anioacademico',
            name='nota_aprobacion',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='anioacademico',
            name='porcentaje_asistencia_req',
            field=models.PositiveIntegerField(default=75, help_text='Porcentaje mínimo de asistencia para regularizar'),
        ),
        migrations.AddField(
            model_name='inscripcionalumnocomision',
            name='condicion',
            field=models.CharField(choices=[('CURSANDO', 'Cursando'), ('REGULAR', 'Regular'), ('LIBRE', 'Libre')], default='CURSANDO', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcionalumnocomision',
            name='fecha_regularizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se determinó la condición (Regular/Libre)', null=True),
        ),
        migrations.AddField(
            model_name='inscripcionalumnocomision',
            name='nota_cursada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promedio obtenido en la cursada (parciales)', max_digits=4, null=True),
        ),
    ]
