# Generated by Django 5.2 on 2025-12-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0028_anioacademico_cierre_cursada_habilitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionalumnocomision',
            name='estado_inscripcion',
            field=models.CharField(choices=[('CURSANDO', 'Cursando'), ('REGULAR', 'Regular'), ('LIBRE', 'Libre'), ('APROBADA', 'Aprobada'), ('DESAPROBADA', 'Desaprobada')], default='CURSANDO', max_length=20),
        ),
    ]
