# Generated by Django 5.2 on 2025-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0029_alter_inscripcionalumnocomision_estado_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='dvh',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionmesaexamen',
            name='dvh',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
