# Generated by Django 5.2 on 2025-12-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0030_calificacion_dvh_inscripcionmesaexamen_dvh'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Número'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alumno_comision', 'tipo', 'numero')},
        ),
    ]
