# Generated by Django 5.2 on 2025-12-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0031_alter_calificacion_unique_together_and_more'),
        ('administracion', '0005_alter_certificado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='plan_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='administracion.planestudio'),
        ),
    ]
