# Generated by Django 5.2 on 2025-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0032_alumno_plan_estudio'),
        ('institucional', '0019_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaexamen',
            name='tribunal',
            field=models.ManyToManyField(help_text='Docentes que conforman el tribunal', limit_choices_to={'empleado__usuario__groups__name': 'Docente'}, related_name='tribunales_examen', to='institucional.persona'),
        ),
    ]
